title: 5C4T3R - Smart Contract Security Engineer
email: 0xscater@gmail.com
description: >-
  Smart Contract CTF Writeups, Exploits, and Security Research.
baseurl: "" # leave empty for GitHub Pages
url: "https://github.com/BLOCK-PROGRAMR" # your GitHub pages URL
plugins:
  - jekyll-feed
  # - jekyll-tagging


tag_page_layout: tag
tag_page_dir: tag

taxonomies:
  tag: tags
  
theme: minima
show_excerpts: true

social_links:
  github: https://github.com/BLOCK-PROGRAMR
  twitter: https://x.com/0x_Scater
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
